version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - apt install enchant-2

sphinx:
  configuration: docs_src/conf.py

python:
  install:
    - path: .
      extra_requirements:
        - docs
    - path: adorable
